apiVersion: v1
kind: Pod
metadata:
  name: dockerdemo-pod
  labels:
    app: dockerdemo
spec:
  containers:
    - name: dockerdemo
      image: dockerdemo:v1
      ports:
        - containerPort: 8080
