spring.kafka.consumer.bootstrap-servers = localhost:9092
spring.kafka.consumer.group-id = groupId
spring.kafka.consumer.auto-offset-reset = earliest
spring.kafka.consumer.key-deserializer = org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer = org.apache.kafka.common.serialization.StringDeserializer

#spring.datasource.url = jdbc:mysql://localhost:3306/wikimedia?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
#spring.datasource.username = root
#spring.datasource.password = root

# Enable the H2 console for web access
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JDBC URL for in-memory H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.show_sql = true
spring.jpa.properties.hibernate.use_sql_comments = true
spring.jpa.properties.hibernate.format_sql = true

spring.kafka.topic.name = wikimedia

